[package]
name = "rectangles"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "calculate area of rectangle"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
