[package]
name = "rectangles"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repo = "https://github.com/Meow-purr/rectangles"
description = "calculate area of rectangle"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
